export type GeneratorStatus = 'verified' | 'candidate' | 'unverified';
export type GeneratorEntry = { id: string; label: string; path: string; status: GeneratorStatus; runbook?: string; invocation?: string; notes?: string };
export type Topology = { id: string; name: string; description: string; inputType: string; deviceCount?: number; generator: GeneratorEntry; alternatives?: GeneratorEntry[]; devices: string[]; nets: string[] };
export type Circuit = { id: string; name: string; description: string; status: 'available' | 'coming-soon'; topologies: Topology[] };

export const technologies = [{
  id: 'tsmcN65', name: 'TSMC N65', status: 'Supported',
  devices: ['nch', 'pch', 'nch_25', 'pch_25', 'nch_mac', 'pch_mac'],
  note: 'Repository-verified Cadence IC6.1.7 / tsmcN65 platform. Device variants still require PDK/CDF confirmation when not explicitly validated.'
}];

const fiveT: Topology = {
  id: '5t-ota', name: '5T OTA',
  description: 'NMOS differential pair with PMOS current-mirror active load and NMOS tail source.',
  inputType: 'NMOS differential input', deviceCount: 5,
  generator: {
    id: '5t-totalw-v2', label: '5T_OTA_PMOS_TOTALW_V2_20260812.il',
    path: 'canonical/5t-ota/5T_OTA_PMOS_TOTALW_V2_20260812.il', status: 'candidate',
    runbook: 'runbooks/RUN_5T_OTA_TOTALW_V2_20260812.md',
    invocation: 'Create5TOTA_PMOS_TOTALW_V2_20260812()',
    notes: 'Current TotalW-first artifact. Repository marks it current, but this does not imply electrical-performance verification.'
  },
  alternatives: [{
    id: '5t-pmos-mac-v1', label: '5T_OTA_PMOS_INPUT_MAC_V1_20260814.il',
    path: 'canonical/5t-ota/5T_OTA_PMOS_INPUT_MAC_V1_20260814.il', status: 'candidate',
    runbook: 'skills/5t-ota-pmos-mac/SKILL.md', invocation: 'Create5TOTA_PMOSIN_MAC_V1_20260814()',
    notes: 'PMOS-input pch_mac/nch_mac flow. User-run topology/CDF checks are recorded; electrical performance is unverified.'
  }],
  devices: ['M1/M2: differential input pair', 'M3/M4: PMOS current-mirror load', 'M5: NMOS tail current source'],
  nets: ['VINP', 'VINN', 'MIRROR', 'VOUT', 'TAIL', 'VDD', 'VSS', 'VBN_TAIL']
};

const telescopic: Topology = {
  id: 'telescopic-ota', name: 'Telescopic OTA',
  description: 'NMOS differential input with cascoding and differential outputs; VDC bias is generated by the canonical flow.',
  inputType: 'NMOS differential input', deviceCount: 9,
  generator: {
    id: 'telescopic-v7', label: 'Telescopic_OTA_NMOS_Diff_TotalW_V7_VDC_InputBias_OutputPins_20260812.il',
    path: 'canonical/telescopic-ota/Telescopic_OTA_NMOS_Diff_TotalW_V7_VDC_InputBias_OutputPins_20260812.il', status: 'verified',
    runbook: 'runbooks/RUN_telescopic_ota_v7_20260812.md',
    invocation: 'CreateTelescopicOTA_NMOS_Diff_TotalW_V7_VDC_InputBias_OutputPins_20260812()',
    notes: 'Canonical schematic-generation reference. Check & Save was verified; performance is not verified.'
  },
  devices: ['M1/M2: input pair', 'M3/M4: lower cascodes', 'M5/M6: folded/top devices', 'M7/M8: PMOS load pair', 'M9: tail/sink'],
  nets: ['VINP', 'VINN', 'VOUTP', 'VOUTN', 'VDD', 'VSS', 'VBN_TAIL', 'VBN_CAS', 'VBP_CAS', 'VBP_LOAD']
};

const folded: Topology = {
  id: 'folded-cascode-ota', name: 'Folded Cascode OTA',
  description: 'NMOS input pair with PMOS top/folded devices and NMOS lower sinks; single-ended output on the right branch.',
  inputType: 'NMOS differential input', deviceCount: 11,
  generator: {
    id: 'folded-totalw-v1', label: 'Folded_Cascode_OTA_NMOS_TotalW_V1_20260814.il',
    path: 'canonical/folded-cascode-ota/Folded_Cascode_OTA_NMOS_TotalW_V1_20260814.il', status: 'candidate',
    runbook: 'runbooks/RUN_Folded_Cascode_OTA_TotalW_V1_20260814.md',
    invocation: 'CreateFoldedCascodeOTA_NMOS_TotalW_V1_20260814()',
    notes: 'Current TotalW-first candidate. Not Cadence-verified yet and performance is not verified.'
  },
  devices: ['M1/M2: input pair', 'M3/M4: PMOS top pair', 'M5/M6: PMOS folded pair', 'M7/M8: NMOS folded pair', 'M9/M10: NMOS sinks', 'M11: NMOS tail'],
  nets: ['VINP', 'VINN', 'VOUT', 'NLEFT', 'NRIGHT', 'FOLD_L', 'VDD', 'VSS', 'VBP1', 'VBP2', 'VBN1', 'VBN2', 'VBN_TAIL']
};

export const circuits: Circuit[] = [
  { id: 'ota', name: 'OTA', description: 'Operational Transconductance Amplifier', status: 'available', topologies: [fiveT, telescopic, folded] },
  { id: 'current-mirror', name: 'Current Mirror', description: 'Bias and current generation', status: 'coming-soon', topologies: [] },
  { id: 'differential-pair', name: 'Differential Pair', description: 'Input differential stage', status: 'coming-soon', topologies: [] },
  { id: 'bandgap', name: 'Bandgap Reference', description: 'Precision voltage reference', status: 'coming-soon', topologies: [] },
  { id: 'ldo', name: 'LDO', description: 'Low-dropout regulator', status: 'coming-soon', topologies: [] },
  { id: 'comparator', name: 'Comparator', description: 'Decision circuit', status: 'coming-soon', topologies: [] }
];

export const getCircuit = (id: string) => circuits.find((c) => c.id === id);
export const getTopology = (circuitId: string, topologyId: string) => getCircuit(circuitId)?.topologies.find((t) => t.id === topologyId);
